In [16]:
#这个主要记录是dynamic programming, 动态规划的问题


#动态规划　背包问题
# 这里使用的是　吉他，音响，电脑，手机
#其中　w吉他＝１，w音响=4，w电脑＝３，w手机＝１
#　　　p吉他＝1500, p音响＝3000, p电脑＝2000,p手机＝2000
import numpy as np
w=[0,1,4,3,1]  #n个物体的重量，w[0]没有任何意义
p=[0,1500,3000,2000,2000]#n个物体的价值，p[0]没有任何作用和意义

n=len(w)-1#n的个数
m=4#背包的载重量

#装入背包的物体，元素为True时,对应物体被装入x[0],无任何作用
x=[False for raw in range(n+1)]
print(x)
v=0

#optp[i][j]表示在前i个物体中，能够载入重量为j的背包的物体的最大价值
optp=[[0 for col in range(m+1) for raw in range(n+1)]]
#optp 做了一个n*m的全零矩阵，n行为物件，m列为背包重量
optp_1=np.zeros([m+1,n+1])
print(optp_1)
print(optp)

def knpsack_dynamic(w,p,n,m,x):
    #计算optp[i][j]
    for i in range(1,n+1):#物品一件件来
        for j in range(1,m+1):#j为子载包的重量，寻找能够承载物品的子背包
            
            if j>=w[j]:#当背包的载重量大于物品的重量时，才考虑放不放进去
                
                #optp[i-1][j]是上一个单元的值，即上一个物品的价值
                #optp[i-1][j-w[i]]为剩余空间的价值
                optp_1[i][j]=max(optp_1[i-1][j],optp_1[i-1][j-w[i]]+p[i])
            else:
                #如果超重，则用上一个单元／行的价值，因为都是最优的
                optp_1[i][j]=optp_1[i-1][j]
                
                
    #递推装入背包的物体，寻找跳边的地方，从最后开始逆推
    j=m
    for i in range(n,0,-1):
        if optp_1[i][j]>optp_1[i-1][j]:
            x.append(i)
            j=j-w[i]
    
    #返回最大价值，即表格中最后一行最后一列的值
    v=optp_1[n][m]
    return v

print(str(knpsack_dynamic(w,p,n,m,x)))
print(x)

[False, False, False, False, False]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
6500.0
[False, False, False, False, False, 4, 2, 1]


5
